# Android_v1.0
# 基础设置
mixed-port: 7890
redir-port: 7891
tproxy-port: 1536
mode: Rule
allow-lan: true
geodata-mode: false
geo-auto-update: false
geo-update-interval: 24
unified-delay: true
tcp-concurrent: true
enable-process: true
log-level: silent
find-process-mode: always
global-client-fingerprint: chrome
external-controller: 0.0.0.0:9090
#面板默认 Meta 可选 Yacd / Zash 重启模块即可加载
external-ui: /data/adb/box_bll/panel/Meta/
secret: ""
# —————————
#####################
#修改配置文件保存时，建议重启模块服务/重载配置.
#####################

# 节点记忆
profile:
  store-selected: true
  store-fake-ip: true
# —————————

# 嗅探模块
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "Mijia Cloud"
# —————————

# 网卡模块
tun:
  enable: true #true 开 #false 关
  device: meta
  stack: system
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  strict-route: true
  auto-redirect: false
  auto-detect-interface: true
  route-exclude-address:
  - 192.168.0.0/16
  - fc00::/7
  exclude-package: # 游戏卡顿可添加包名
    - com.tencent.mm
    - com.tencent.tmgp.sgame
    - com.ss.android.ugc.aweme
    - com.android.providers.downloads.ui
# —————————

# DNS模块
dns:
  enable: true
  prefer-h3: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/15
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "connect.rom.miui.com"
    - "localhost.ptlogin2.qq.com"
    - "*.market.xiaomi.com"
  default-nameserver:
    - 119.29.29.29
    - 223.6.6.6
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
# —————————

# 健康检查
p: &p
  type: http
  interval: 86400
  health-check:
    enable: true
    url: https://www.gstatic.com/generate_204
    interval: 300
# —————————

# 订阅地址相关
A: &A
  filter: "^(?!.*(订阅|群|账户|流量|有效期|时间|官网)).*$"
  use:
  - 1.主要地址
  - 2.备用地址
  - 3.额外地址

All: &All
  type: url-test
  use:
  - 1.主要地址
  - 2.备用地址
  - 3.额外地址
  
proxy-providers:
  1.主要地址:
    <<: *p
    url: "引入您的Clash订阅链接地址"
    
  2.备用地址:
    <<: *p
    url: "引入您的Clash订阅链接地址"
  
  3.额外地址:
    <<: *p
    url: "引入您的Clash订阅链接地址"
# —————————

proxies:
  - {name: 🌎 全球直连, type: direct, udp: true}
  - {name: 🚫 拒绝连接, type: reject}
  - {name: 🌐 DNS_Hijack, type: dns}

name_proxies: &name_proxies
    type: select
    proxies:
      - 🚀 节点选择
      - ♻️ 手动切换1
      - ♻️ 延迟最低
      - ♻️ 故障转移
      - ♻️ 负载均衡
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🌍 其它地区
      - 🌎 全球直连
# —————————

proxy-groups:
  - name: 🎯 总模式
    <<: *name_proxies

  - name: 🚀 节点选择
    type: select
    proxies:
      - ♻️ 延迟最低
      - 🌎 全球直连
    <<: *A

  - name: ♻️ 手动切换1
    type: select
    proxies:
      - ♻️ 延迟最低
      - 🌎 全球直连
    <<: *A

  - name: ♻️ 延迟最低
    type: url-test
    <<: *A
  
  - name: ♻️ 故障转移
    type: fallback
    <<: *A
  
  - name: ♻️ 负载均衡
    type: load-balance
    strategy: round-robin
    <<: *A

  - name: 📲 电报信息
    <<: *name_proxies

  - name: 🤖 OpenAI
    <<: *name_proxies

  - name: 🎬 油管媒体
    <<: *name_proxies

  - name: 📸 TikTok
    <<: *name_proxies

  - name: 📱 脸书社交
    <<: *name_proxies

  - name: 📹 奈飞媒体
    <<: *name_proxies

  - name: 📢 谷歌服务
    <<: *name_proxies

  - name: 📣 谷歌推送
    <<: *name_proxies

  - name: 🎮 Discord
    <<: *name_proxies

  - name: Ⓜ️ 微软服务
    <<: *name_proxies

  - name: 🍎 苹果服务
    <<: *name_proxies

  - name: 🎹 网易音乐
    <<: *name_proxies

  - name: 🛑 广告拦截
    type: select
    proxies:
      - 🚫 拒绝连接
      - 🌎 全球直连

  - name: 🐋 漏网之鱼
    <<: *name_proxies

  - name: 🇭🇰 香港节点
    filter: "^(?=.*(港|HK|hk|Hong Kong|HongKong|hongkong)).*$"
    <<: *All

  - name: 🇯🇵 日本节点
    filter: "^(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)).*$"
    <<: *All

  - name: 🇺🇲 美国节点
    filter: "^(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)).*$"
    <<: *All

  - name: 🇨🇳 台湾节点
    filter: "^(?=.*(台|新北|彰化|TW|Taiwan)).*$"
    <<: *All

  - name: 🇸🇬 狮城节点
    filter: "^(?=.*(新加坡|坡|狮城|SG|Singapore)).*$"
    <<: *All

  - name: 🌍 其它地区
    filter: "^(?!.*(港|HK|hk|Hong Kong|HongKong|hongkong|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|台|新北|彰化|TW|Taiwan|新加坡|坡|狮城|SG|Singapore|灾|网易|Netease|订阅|群|账户|流量|有效期|时间|官网)).*$"
    <<: *All
# —————————

rule-anchor:
  RuleDefault: &RuleDefault
    {type: http, behavior: classical, format: text, interval: 86400}
  Domain: &Domain
    {type: http, behavior: domain, format: mrs, interval: 86400}
  IP: &IP
    {type: http, behavior: ipcidr, format: mrs, interval: 86400}
# —————————

rule-providers:
  CN_IP:
    <<: *IP
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"
    
  private_Lan:
    <<: *IP
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"

  CN_域名:
    <<: *Domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"

  category-ads-all:
    <<: *Domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ads-all.mrs"

  TikTok:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list"

  Facebook:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Facebook/Facebook.list"

  Telegram:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram.list"

  YouTube:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list"

  Google:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list"

  GoogleFCM:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GoogleFCM/GoogleFCM.list"

  Microsoft:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.list"

  Apple:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple.list"

  OpenAI:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list"

  Netflix:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Netflix/Netflix.list"

  Discord:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Discord/Discord.list"

  NetEaseMusic:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/NetEaseMusic/NetEaseMusic.list"
# —————————

rules:
  - DST-PORT,53,🌐 DNS_Hijack
  - AND,((PROCESS-NAME,mihomo),(NOT,((IN-TYPE,inner)))),REJECT
  - AND,((PROCESS-NAME,clash),(NOT,((IN-TYPE,inner)))),REJECT
  - RULE-SET,NetEaseMusic,🎹 网易音乐
  - RULE-SET,Discord,🎮 Discord
  - RULE-SET,TikTok,📸 TikTok
  - RULE-SET,YouTube,🎬 油管媒体
  - RULE-SET,Netflix,📹 奈飞媒体
  - RULE-SET,Facebook,📱 脸书社交
  - RULE-SET,OpenAI,🤖 OpenAI
  - RULE-SET,Google,📢 谷歌服务
  - RULE-SET,GoogleFCM,📣 谷歌推送
  - RULE-SET,Apple,🍎 苹果服务
  - RULE-SET,Microsoft,Ⓜ️ 微软服务
  - RULE-SET,Telegram,📲 电报信息
  - RULE-SET,category-ads-all,🛑 广告拦截
  - RULE-SET,CN_域名,🌎 全球直连
  - RULE-SET,CN_IP,🌎 全球直连,no-resolve
  - RULE-SET,private_Lan,🌎 全球直连,no-resolve
  - MATCH,🐋 漏网之鱼
# —————————